import { PERMISSIONS } from "./permissions.js";

export const ROLES = {
  ADMIN: [
    PERMISSIONS.SYSTEM_ALL,
  ],

  LIBRARIAN: [
    PERMISSIONS.BOOK_CREATE,
    PERMISSIONS.BOOK_UPDATE,
    PERMISSIONS.BOOK_DELETE,
    PERMISSIONS.BOOK_READ,
  ],

  READER: [
    PERMISSIONS.BOOK_READ,
    PERMISSIONS.BOOK_BORROW,
    PERMISSIONS.BOOK_RETURN,
  ],
};
